# Configuration file for a Q*BERT clone - https://strategywiki.org/wiki/Q*bert

[[tile]]
    width=32  # automatically set via given/chosen resolution?
    height=32
    touched="path/to/res"
    untouched="path/to/res"
    # add subtables for specific types of tiles . . .

[[map]]  # layers ? divide by level?
    level=1  # TODO?
    viewportposition=[ 0, 0 ]  # Also define camera/viewport start-position for level via upper left coordinates?

    [[layers.tiles]]  # rename to map/tilemap?

        # TODO map layers by aspect ratio? viewport/window is always 16 units wide by 12/10/9 units tall . . .
        # TODO remember to center the projected map (below) via the camera offset - e.g. screen.x += SCREEN_WIDTH_HALF
        [[layers.tiles.map]]
            aspectratio='4:3'  # irrelevant? map to viewportposition at [ 12, 9 ] ?
            layer=[  # rename to map/layout?  # perhaps don't do this? use relative coordinates/padding instead? e.g., padding=2\nscore="upper left" ?
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        ]

    [[layers.characters]]  # player, balls, snake, discs, etc.

    [[layers.ui]]


# TODO is this necessary . . . ? - not really
[[display]]

    [[display.aspectratio]]
        '4:3'=[ [ 640, 480 ],
                [ 800, 600 ],
                [ 960, 720 ],
                [ 1024, 768 ],
                [ 1280, 960 ],
                [ 1400, 1050 ],
                [ 1440, 1080 ],
                [ 1600, 1200 ],
                [ 1856, 1392 ],
                [ 1920, 1440 ],
                [ 2048, 1536 ]
          ]

    [[display.aspectratio]]
        '16:10'=[ [ 1280, 800 ],
                  [ 1440, 900 ],
                  [ 1680, 1050 ],
                  [ 1920, 1200 ],
                  [ 2560, 1600 ]
        ]

    [[display.aspectratio]]
        '16:9'=[ [ 1024, 576 ],
                 [ 1152, 648 ],
                 [ 1280, 720 ],
                 [ 1366, 768 ],
                 [ 1600, 900 ],
                 [ 1920, 1080 ],  # FHD
                 [ 2560, 1440 ],  # QHD
                 [ 3840, 2160 ],  # 4K
                 [ 7680, 4320 ]   # 8K
        ]
