# Configuration file for a Q*BERT clone - https://strategywiki.org/wiki/Q*bert
# TODO add TMX support? - http://doc.mapeditor.org/en/stable/reference/support-for-tmx-maps/#id1

# The variables below are overridden by a level if they are specified in that level
# The origin defines the map array coordinate to place at the top center position of the screen after loading the map
origin=[ 0, 0 ]
scorepertile=30
bonus=1000  # bonus points for completing this level
windowicon='blocks|PNG|abstract-tiles|abstractTile_32.png'
background='background.png'
music='audio|music|Hypnotic-Puzzle.mp3'

[player]
    sprite='player|star_09.png'  # Folder for player sprites
    start=[ 1,1 ]  # grid starting position - does not take 'origin' into account
    lives=4

[tiles]
    # Using pipe character '|' as platform agnostic path separator - this assumes the tiles are under res/
    untouched='blocks|PNG|abstract-tiles|abstractTile_12.png'
    touched='blocks|PNG|abstract-tiles|abstractTile_32.png'
    [tiles.audio]
        untouched='audio|effects|PowerUp8.mp3'
        touched='audio|effects|PowerUp8.mp3'
        offmap='audio|effects|PowerUp8.mp3'

[[level]]  # Add rounds?
    id=1
    # For this level, regardless of aspect ratio, the screen should fit at least 6 tiles high so that the pyramid is completely shown
    minscreentileheight=6  # diagonal/vertical height of pyramid map in tiles
    # 0 = no tile
    # 1 = platform tile
    # 2 = disc
    map=[    # 9x9 grid/2
# top center of screen
        [0,0,0,0,0,0,2,0,0], # rightmost on screen
        [0,1,1,1,1,1,1,1,0],
        [0,1,1,1,1,1,1,0],
        [0,1,1,1,1,1,0],
        [0,1,1,1,1,0],  # bottom of screen
        [0,1,1,1,0],
        [2,1,1,0],
        [0,1,0],
        [0,0]
# leftmost on screen
    ]

    [level.tiles]
        untouched='res/blocks/PNG/abstract-tiles/abstractTile_12.png'
        touched='res/blocks/PNG/abstract-tiles/abstractTile_32.png'

[[level]]
    id=2
    # etc . . .
